from src.features.feature_engineering import orchestrate_features
from pathlib import Path
from typing import Any
import pandas as pd


def run_features_pipeline(
    logs_dataframe: pd.DataFrame, raw_data: dict[str, Any]
) -> None:
    """Orchestrates the generation and persistance of a dataset that contains
    the features generated by the module feature engineering.

    Args:
        logs_dataframe: DF of parsed logs
        raw_data: raw data loaded from the config file.
    """

    dataset_filename = _make_output_directory() / "features.csv"

    features_dataframe = orchestrate_features(
        logs_dataframe, raw_data["feature_thresholds"], raw_data["service"]
    )

    features_dataframe.to_csv(dataset_filename, index=False)


def _make_output_directory() -> Path:
    """Makes the directory to save the outputs.

    Returns:
        Path object with the directory.
    """

    parent_path = Path(__file__).resolve().parents[1]
    dataset_dir = parent_path / "output" / "datasets"
    dataset_dir.mkdir(parents=True, exist_ok=True)

    return dataset_dir
