# Log Analysis Pipeline Configuration

paths:
  raw_log: data/raw/access_logs/
  output_dir: output/

columns:
  host: str
  identity: str
  user: str
  timestamp: datetime.datetime
  method: str
  endpoint: str
  protocol_version: str
  http_response: int
  response_size: int

expected_values:
  method:
    - GET
    - POST
    - HEAD
  protocol_version:
    - HTTP/1.0
    - HTTP/V1.0
  http_response:
    - 100
    - 599

metric_thresholds:
  response_size:
    low: 669
    normal: 3100
    high: max
